server:
  port: 8086
  
spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
      - id: product-service
        uri:
          lb://product-service
        predicates:
        - Path=/eshoppingzone/product/**
        
      - id: cart-service
        uri:
          lb://cart-service
        predicates:
        - Path=/eshoppingzone/cart/**